(WIP)[RN-781]: ios/android quick links
bitpay/bitpay-app pull request #589
Opened 2022-12-14 14:35 UTC by rastajpa

waiting for icons...

2022-12-16 16:28 UTC, cmgustavo commented on src/constants/shortcuts.ts
> +    title: 'Buy Cryptos',
Just a typo: "Buy Crypto"
![Screenshot 2022-12-16 at 13 27 26](https://user-images.githubusercontent.com/237435/208144296-36eb0f05-cc79-432f-9ef4-693273743199.png)

2022-12-16 16:40 UTC, cmgustavo approved these changes
Nice work! Tested on iOS and Android
LGTM 👍🏼

2022-12-16 20:17 UTC, cmgustavo requested changes
I found an issue specifically on Android. The event `quickActionShortcut` is permanently called every time you enter (or back) to Home. So, if you click on a shortcut function (receive, send, buy, or swap), then you go back to Home, it will return to the view "Select a currency". Also, if you go back, and change the tab, it's fine. But if you return to Home, it will redirect again to "Select a currency".

2022-12-19 13:33 UTC, rastajpa commented on src/constants/shortcuts.ts
> +    title: 'Buy Cryptos',
ouch! ty!

2022-12-19 13:35 UTC, rastajpa commented
> I found an issue specifically on Android. The event `quickActionShortcut` is permanently called every time you enter (or back) to Home. So, if you click on a shortcut function (receive, send, buy, or swap), then you go back to Home, it will return to the view "Select a currency". Also, if you go back, and change the tab, it's fine. But if you return to Home, it will redirect again to "Select a currency".

thank you, I'm working on a fix

2022-12-19 19:37 UTC, cmgustavo submitted a review, later dismissed
Worked on Android! 👍🏼

2022-12-20 13:14 UTC, cmgustavo approved these changes
ACK! 🚀

2022-12-27 16:00 UTC, Gamboster approved these changes
LGTM
Nice work!!

2022-12-28 16:38 UTC, merged